spring:
  application:
    name: Nexora Campus


platform:
  datasource:
    url: jdbc:postgresql://${PLATFORM_DB_HOST:localhost}:${PLATFORM_DB_PORT:5432}/${PLATFORM_DB_NAME:PLATFORM_campus}
    username: ${PLATFORM_DB_USER:postgres}
    password: ${PLATFORM_DB_PASSWORD:root}
    driverClassName: org.postgresql.Drivers
    # connectionTimeout: ${PLATFORM_DB_CONNECTION_TIMEOUT:20000}
    # maxPoolSize: ${PLATFORM_DB_MAX_POOL_SIZE:250}
    # idleTimeout: ${PLATFORM_DB_IDLE_TIMEOUT:300000}
    # minIdle: ${PLATFORM_DB_MIN_IDLE:5}
    # poolName: ${PLATFORM_DB_POOL_NAME:PLATFORMdb-connection-pool}


